spring:
    datasource:
        url: jdbc:mysql://localhost:3306/playtube?serverTimezone=Shanghai&?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    servlet:
        multipart:
            max-request-size: 30MB
            max-file-size: 30MB
    data:
        redis:
            host: 8.130.154.240
            password: 123456
            port: 6379

#rocketmq
rocketmq:
    nameServer: 43.138.5.79:9876

#fdfs
fdfs:
    #连接超时时间
    connect-timeout: 600
    #读取时间
    so-timeout: 1500
    #缩略图
    thumb-image:
        height: 150
        width: 150
    #Tracker服务，确保tracker storage nginx已经启动
    tracker-list: 43.138.5.79:22122
    pool:
        jmx-enabled: false
    http:
        storage-addr: http://43.138.5.79:8888/group1/

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.playtube.dao
    configuration:
        map-underscore-to-camel-case: true